tags:
  - name: Buckets
    description: api for managing buckets
  - name: Documents
    description: api for managing documents
securityDefinitions:
  login:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Document:
    type: object
    properties:
      key:
        type: string
      owner:
        type: string
      created:
        type: string
      version:
        type: string
      latest:
        type: boolean
      description:
        type: string
      size:
        type: integer
        format: int64
      content-type:
        type: string
      metadata:
        $ref: '#/definitions/Metadata'
    required:
      - key
      - owner
      - created
  Bucket:
    type: object
    properties:
      name:
        type: string
      created:
        type: string
      owner:
        type: string
      versioned:
        type: boolean
  Metadata:
    type: object
    additionalProperties:
      type: string
  ResponseSuccess:
    type: object
    properties:
      success:
        type: boolean
    additionalProperties: false
    required:
      - success
produces:
  - application/json
paths:
  '/services/rest/v1/meta/':
    get:
      tags:
        - Buckets
      parameters:
        - in: query
          name: limit
          description: ''
          required: false
          type: integer
          format: int64
        - in: query
          name: page
          description: ''
          required: false
          type: integer
          format: int64
      responses:
        '200':
          schema:
            type: array
            items:
              $ref: '#/definitions/Bucket'
          description: ''
      summary: list all buckets
  '/services/rest/v1/meta/{bucket}':
    get:
      tags:
        - Documents
      parameters:
        - in: query
          name: limit
          description: ''
          required: false
          type: integer
          format: int64
        - in: query
          name: page
          description: ''
          required: false
          type: integer
          format: int64
        - in: path
          name: bucket
          description: ''
          required: true
          type: string
      responses:
        '200':
          schema:
            type: array
            items:
              $ref: '#/definitions/Document'
          description: ''
      summary: list all documents of the bucket
    delete:
      tags:
        - Buckets
      parameters:
        - in: path
          name: bucket
          description: ''
          required: true
          type: string
      responses:
        '200':
          schema:
            $ref: '#/definitions/ResponseSuccess'
          description: ''
      summary: delete the selected bucket
    put:
      tags:
        - Buckets
      parameters:
        - in: path
          name: bucket
          description: ''
          required: true
          type: string
      responses:
        '200':
          schema:
            $ref: '#/definitions/ResponseSuccess'
          description: ''
      summary: create a new bucket
  '/services/rest/v1/content/{bucket}/{key}':
    get:
      tags:
        - Documents
      parameters:
        - in: path
          name: bucket
          description: ''
          required: true
          type: string
        - in: path
          name: key
          description: ''
          required: true
          type: string
        - in: query
          name: version
          description: ''
          required: false
          type: string
      summary: get the selected document
      responses:
        default:
          description: ''
    delete:
      tags:
        - Documents
      parameters:
        - in: path
          name: bucket
          description: ''
          required: true
          type: string
        - in: path
          name: key
          description: ''
          required: true
          type: string
        - in: query
          name: version
          description: ''
          required: false
          type: string
      responses:
        '200':
          schema:
            $ref: '#/definitions/ResponseSuccess'
          description: ''
      summary: delete the selected document
    put:
      tags:
        - Documents
      parameters:
        - in: path
          name: bucket
          description: ''
          required: true
          type: string
        - in: path
          name: key
          description: ''
          required: true
          type: string
        - in: query
          name: version
          description: ''
          required: false
          type: string
      responses:
        '200':
          schema:
            $ref: '#/definitions/Document'
          description: ''
      summary: put a new document
  '/services/rest/v1/meta/{bucket}/{key}':
    get:
      tags:
        - Documents
      parameters:
        - in: path
          name: bucket
          description: ''
          required: true
          type: string
        - in: path
          name: key
          description: ''
          required: true
          type: string
        - in: query
          name: versions
          description: ''
          required: false
          type: boolean
          default: false
      summary: get the selected document
      responses:
        '200':
          schema:
            $ref: '#/definitions/Document'
          description: ''
    delete:
      tags:
        - Documents
      parameters:
        - in: path
          name: bucket
          description: ''
          required: true
          type: string
        - in: path
          name: key
          description: ''
          required: true
          type: string
        - in: query
          name: version
          description: ''
          required: false
          type: string
      responses:
        '200':
          schema:
            $ref: '#/definitions/ResponseSuccess'
          description: ''
      summary: delete the selected document
    put:
      tags:
        - Documents
      parameters:
        - in: path
          name: bucket
          description: ''
          required: true
          type: string
        - in: path
          name: key
          description: ''
          required: true
          type: string
        - in: query
          name: version
          description: ''
          required: false
          type: string
      responses:
        '200':
          schema:
            $ref: '#/definitions/Document'
          description: ''
      summary: put a new document

consumes:
  - application/json
info:
  title: Ladon Datacenter Edition
  version: 0.0.1
  description: Ladon Datacenter Edition REST API
swagger: '2.0'
basePath: /
