tags:
  - name: Data
    description: binary api for documents
  - name: Meta
    description: metadata api for documents
securityDefinitions:
  login:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Document:
    type: object
    properties:
      key:
        type: string
      user:
        type: string
      created:
        type: string
      version:
        type: string
      latest:
        type: boolean
      description:
        type: string
      size:
        type: integer
        format: int64
      content-type:
        type: string
    additionalProperties: false
    required:
      - key
      - user
      - created
  Response18209:
    type: object
    properties:
      success:
        type: boolean
    additionalProperties: false
    required:
      - success
  Response18210:
    type: object
    properties:
      success:
        type: boolean
    additionalProperties: false
    required:
      - success
  Response18211:
    type: object
    properties:
      result:
        type: integer
        format: int64
    additionalProperties: false
    required:
      - result
  Response18212:
    type: object
    properties:
      result:
        type: integer
        format: int64
    additionalProperties: false
    required:
      - result
produces:
  - application/json
paths:
  '/services/rest/v1/meta/{bucket}':
    get:
      tags:
        - Meta
      parameters:
        - in: query
          name: count
          description: ''
          required: false
          type: integer
          format: int64
        - in: query
          name: page
          description: ''
          required: false
          type: integer
          format: int64
        - in: path
          name: bucket
          description: ''
          required: true
          type: string
      responses:
        '200':
          schema:
            type: array
            items:
              $ref: '#/definitions/Document'
          description: ''
      summary: list all documents of the authenticated user
  '/services/rest/v1/data/{bucket}/{key}':
    get:
      tags:
        - Data
      parameters:
        - in: path
          name: bucket
          description: ''
          required: true
          type: string
        - in: path
          name: key
          description: ''
          required: true
          type: string
        - in: query
          name: version
          description: ''
          required: false
          type: string
      summary: get the selected document
      responses:
        default:
          description: ''
    delete:
      tags:
        - Data
      parameters:
        - in: path
          name: bucket
          description: ''
          required: true
          type: string
        - in: path
          name: key
          description: ''
          required: true
          type: string
        - in: query
          name: version
          description: ''
          required: false
          type: string
      responses:
        '200':
          schema:
            $ref: '#/definitions/Response18209'
          description: ''
      summary: delete the selected document
    put:
      tags:
        - Data
      parameters:
        - in: path
          name: bucket
          description: ''
          required: true
          type: string
        - in: path
          name: key
          description: ''
          required: true
          type: string
        - in: query
          name: version
          description: ''
          required: false
          type: string
      responses:
        '200':
          schema:
            $ref: '#/definitions/Document'
          description: ''
      summary: put a new document
  '/services/rest/v1/meta/{bucket}/{key}':
    get:
      tags:
        - Meta
      parameters:
        - in: path
          name: bucket
          description: ''
          required: true
          type: string
        - in: path
          name: key
          description: ''
          required: true
          type: string
        - in: query
          name: versions
          description: ''
          required: false
          type: boolean
          default: false
      summary: get the selected document
      responses:
        default:
          description: ''
    delete:
      tags:
        - Meta
      parameters:
        - in: path
          name: bucket
          description: ''
          required: true
          type: string
        - in: path
          name: key
          description: ''
          required: true
          type: string
        - in: query
          name: version
          description: ''
          required: false
          type: string
      responses:
        '200':
          schema:
            $ref: '#/definitions/Response18209'
          description: ''
      summary: delete the selected document
    put:
      tags:
        - Meta
      parameters:
        - in: path
          name: bucket
          description: ''
          required: true
          type: string
        - in: path
          name: key
          description: ''
          required: true
          type: string
        - in: query
          name: version
          description: ''
          required: false
          type: string
      responses:
        '200':
          schema:
            $ref: '#/definitions/Document'
          description: ''
      summary: put a new document

consumes:
  - application/json
info:
  title: Ladon Datacenter Edition
  version: 0.0.1
  description: Ladon Datacenter Edition REST API
swagger: '2.0'
basePath: /
